apiVersion: v1
kind: Service
metadata:
  namespace: openshift-route-controller-manager
  name: route-controller-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert
  labels:
    prometheus: route-controller-manager
spec:
  selector:
    route-controller-manager: "true"
  ports:
  - name: https
    port: 443
    targetPort: 8443
