apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:openshift-route-controller-manager
  namespace: openshift-route-controller-manager
rules:
- apiGroups:
    - ""
    - events.k8s.io
  resources:
    - events
  verbs:
    - create
    - patch
    - update
